# Generated by Django 4.1.7 on 2023-04-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afp2', '0002_initial'),
    ]

    operations = [
    ]
