# Generated by Django 4.1.7 on 2023-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp2', '0003_auto_20230405_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
