# Generated by Django 4.1.7 on 2023-04-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp2', '0004_alter_registeruser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
