# Generated by Django 4.1.7 on 2023-04-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afp2', '0006_alter_registeruser_email_alter_registeruser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='k_UserInRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roles_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afp2.roles')),
                ('User_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afp2.registeruser')),
            ],
        ),
    ]
