# Generated by Django 4.1.7 on 2023-05-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afp2', '0008_question_quiz_alter_k_userinroles_roles_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='k_userinroles',
            old_name='Roles_Id',
            new_name='Roles',
        ),
        migrations.RenameField(
            model_name='k_userinroles',
            old_name='User_Id',
            new_name='User',
        ),
    ]
